pipeline{
    agent{
        docker {image 'tomcat:jre21-temurin'}
    }
    stages{
        stage('Testing version'){
            steps{
                ls
                
                sh './version.sh'
            }
        }
    }
}
