pipeline{
    agent{
        docker {image 'tomcat:jre21-temurin'}
    }
    stages{
        stage('Testing version'){
            steps{
                sh '''
                ls
                ls ./
                ./version.sh
                '''
            }
        }
    }
}
